#! /bin/sh
### BEGIN INIT INFO
# Provides:          librecores-rabbitmq-supervisor
# Required-Start:    $remote_fs $network $named
# Required-Stop:     $remote_fs $network $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop librecores RabbitMQ supervisor daemon
# Description:       Start/stop librecores RabbitMQ supervisor daemon
### END INIT INFO

. /lib/lsb/init-functions

. /var/www/site/app/config/symfony-env.sh

WEBDIR=/var/www/site
USER="{{web_user }}"
CTRL_CMD="$WEBDIR/app/console rabbitmq-supervisor:control"

CTRL_CMD="sudo -u $USER -- $CTRL_CMD"

set -e

case "$1" in
  start)
    $CTRL_CMD start
    ;;
  stop)
    $CTRL_CMD stop
    ;;
  reload)
    $CTRL_CMD hup
    ;;
  restart)
    $CTRL_CMD restart
    ;;
  *)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop|restart|reload}" >&2
    exit 1
    ;;
esac

exit 0
