<?php

namespace Librecores\ProjectRepoBundle\Repository;

/**
 * ClassificationHierarchyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassificationHierarchyRepository extends \Doctrine\ORM\EntityRepository
{
}
