<?php

namespace Librecores\ProjectRepoBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Librecores\ProjectRepoBundle\Entity\Commit;
use Librecores\ProjectRepoBundle\Entity\SourceRepo;

/**
 * CommitRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class CommitRepository extends EntityRepository
{
    /**
     * Get the latest commit on the database
     *
     * @return null|Commit
     */
    public function getLatestCommit()
    {
        return $this->findOneBy([], [ 'dateCommitted' => 'DESC']);
    }

    public function clearAllCommits(SourceRepo $repo)
    {
        return $this->createQueryBuilder('c')
                    ->delete()
                    ->where('c.repository = :repo')
                    ->setParameter('repo', $repo)
                    ->getQuery()
                    ->execute();
    }
}
