<?php

namespace Librecores\ProjectRepoBundle\Repository;

/**
 * ProjectClassifierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectClassifierRepository extends \Doctrine\ORM\EntityRepository
{
}
