Vagrant.configure("2") do |config|
    # Configure the box to use
    config.vm.box       = 'precise64'
    config.vm.box_url   = 'http://files.vagrantup.com/precise64.box'

    # Configure the network interfaces
    config.vm.network :private_network, ip:    "192.168.33.10"

    # optionally, you can make some services accessible directly on
    # the host machine's "localhost". Make sure to have no other service
    # running on those ports (e.g. a MySQL server on 3306).
    #config.vm.network :forwarded_port,  guest: 80,    host: 8080
    #config.vm.network :forwarded_port,  guest: 8081,  host: 8081
    #config.vm.network :forwarded_port,  guest: 3306,  host: 3306
    #config.vm.network :forwarded_port,  guest: 27017, host: 27017

    # Configure shared folders
    # uncomment either one of the two versions below. See README.md in the
    # top-level folder for details.
    # WITH NFS
    config.vm.synced_folder ".",  "/vagrant", id: "vagrant-root",type: 'nfs', map_uid: Process.uid, map_gid: Process.gid
    config.vm.synced_folder "..", "/var/www", id: "application", type: 'nfs', map_uid: Process.uid, map_gid: Process.gid

    # WITHOUT NFS
    #config.vm.synced_folder ".",  "/vagrant", id: "vagrant-root"
    #config.vm.synced_folder "..", "/var/www", id: "application"

    # Configure hostmanager
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.include_offline = true
    config.vm.define 'librecores' do |node|
        node.vm.hostname = 'librecores.devel'
        node.vm.network :private_network, ip: '192.168.33.10'
        node.hostmanager.aliases = %w(www.librecores.devel blog.librecores.devel)
    end


    # Configure VirtualBox environment
    config.vm.provider :virtualbox do |v|
        v.name = (0...8).map { (65 + rand(26)).chr }.join
        v.customize [ "modifyvm", :id, "--memory", 512 ]
    end

    # Provision the box
    config.vm.provision :ansible do |ansible|
        ansible.extra_vars = { ansible_ssh_user: 'vagrant' }
        ansible.playbook = "ansible/site.yml"
    end
end
