Vagrant.configure("2") do |config|
    # Configure the box to use
    config.vm.box       = 'ubuntu/trusty64'

    # Configure shared folders
    # uncomment either one of the two versions below. See README.md in the
    # top-level folder for details.
    # WITH NFS
    config.vm.synced_folder ".",  "/vagrant", id: "vagrant-root",type: 'nfs', map_uid: Process.uid, map_gid: Process.gid
    config.vm.synced_folder "..", "/var/www", id: "application", type: 'nfs', map_uid: Process.uid, map_gid: Process.gid

    # WITHOUT NFS
    #config.vm.synced_folder ".",  "/vagrant", id: "vagrant-root"
    #config.vm.synced_folder "..", "/var/www", id: "application"

    # Configure networking (requires hostmanager plugin)
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.include_offline = true
    config.vm.define 'librecores' do |node|
        node.vm.hostname = 'librecores.devel'
        node.vm.network :private_network, ip: '192.168.33.10'
        node.hostmanager.aliases = %w(www.librecores.devel blog.librecores.devel)
    end

    # Configure VirtualBox environment
    config.vm.provider :virtualbox do |v|
        v.name = (0...8).map { (65 + rand(26)).chr }.join
        v.customize [ "modifyvm", :id, "--memory", 1024 ]
    end

    # Provision the box
    config.vm.provision :ansible do |ansible|
        ansible.extra_vars = { ansible_ssh_user: 'vagrant' }
        ansible.playbook = "../ansible/dev-vagrant.yml"
    end
end

