---
# PHP version to be used
# Packages are expected to be named php<php_version>, e.g. php7.0, php7.0-xml,
# etc. The same is true for the binaries.
php_version: 7.4

# PHP extensions, installed from OS packages (preferred)
# All packages are expected to be named "php{{ php_version }}-EXTENSION_NAME"
php_extensions_packaged:
  - dev
  - curl
  - mysql
  - xml
  - bcmath
  - mbstring
  - zip
  - intl

# Development extensions installed through OS packages
# Like php_extensions_packaged, but only available during development
php_devel_extensions_packaged:
  - xdebug

# PHP extensions, installed through PEAR (if not available through OS packages)
php_extensions_pecl: []
#  - { name: "NAME", package: "pecl.php.net/NAME" }

# PHP FPM socket (for web servers)
php_fpm_sock: "/var/run/php/php{{ php_version }}-fpm.sock"

# Major version of nodejs to be used
nodejs_major_version: 10

# RabbitMQ consumers started as service (through the Symfony rabbitmq bundle)
# Uses the rabbitmq:consumer/rabbitmq:multiple-consumer console commands.
rabbitmq_consumers:
  - name: update_project_info
    type: single
# TODO: Fix consumer, currently broken (unable to start)
#  - name: update_github_metadata
#    type: single
  - name: notification
    type: multiple

# Options passed to the RabbitMQ consumer services
# Consume 250 messages per run, allow up to 256 MB of memory for this process
rabbitmq_consumer_options: -vv --memory-limit 256 --messages 250
