# For LibreCores: Keep this in sync with
# https://raw.githubusercontent.com/github/markup/master/Gemfile
# but remove the "gemfile" instruction.
source "http://rubygems.org"

# this is not part of the Gemfile in the github-markup repository, but required
# to actually parse github flavored markdown.
gem "github-markdown"

gem "posix-spawn", :platforms => :ruby
gem "redcarpet", :platforms => :ruby
gem "kramdown", :platforms => :jruby
gem "RedCloth"
gem "commonmarker", "~> 0.18.1"
gem "rdoc", "~>3.6"
gem "org-ruby", "= 0.9.9"
gem "creole", "~>0.3.6"
gem "wikicloth", "=0.8.3"
gem "twitter-text", "~> 1.14"
gem "asciidoctor", "~> 2.0.5"
gem "rake"
